version: "3.8"

services:
  avito-shop-service:
    build: .
    container_name: avito-shop-service
    ports:
      - "8083:8083"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=shop
      - DATABASE_HOST=db
      - JWT_ACCESS_SECRET=mGZSyg__1EeXfuj1V0S-HyT9Nn3eSbPmS2NUpMABOsA=

      - SERVER_PORT=0.0.0.0:8083
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - ./migrations/00000_init_tables.init.sql:/docker-entrypoint-initdb.d/00000_init_tables.init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
networks:
  internal:
